#! /bin/sh

#set -U SXHKD_SHELL /bin/sh

#sxhkd &
kill-and-launch.sh sxhkd

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#compton &
#polybar screen &
#redshift &
kill-and-launch.sh compton
kill-and-launch.sh polybar screen
(source ~/.credentials/location.sh && kill-and-launch.sh redshift "-l $LAT:$LONG")

feh --bg-fill ~/pictures/bg/bg.png

